apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: resumatch-ai
spec:
  parentRefs:
  - name: resumatch-gateway
    sectionName: https
  hostnames:
  - resumatches.com
  - www.resumatches.com
  - www.jaiswal.shop
  - jaiswal.shop
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: backend-service
      port: 8090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: resumatch-ai
spec:
  parentRefs:
  - name: resumatch-gateway
    sectionName: https
  hostnames:
  - resumatches.com
  - www.resumatches.com
  - www.jaiswal.shop
  - jaiswal.shop
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend-service
      port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jaeger-route
  namespace: resumatch-ai
spec:
  parentRefs:
  - name: resumatch-gateway
    sectionName: https
  hostnames:
  - jaeger.jaiswal.shop
  - jaeger.resumatches.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: jaeger-service
      port: 16686
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  parentRefs:
  - name: resumatch-gateway
    namespace: resumatch-ai
    sectionName: https
  hostnames:
  - grafana.jaiswal.shop
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: prometheus-grafana
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
  namespace: monitoring
spec:
  parentRefs:
  - name: resumatch-gateway
    namespace: resumatch-ai
    sectionName: https
  hostnames:
  - prometheus.jaiswal.shop
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: prometheus-kube-prometheus-prometheus
      port: 9090